spring.datasource.url=jdbc:sqlserver://localhost:1433;trustServerCertificate=true;encrypt=true;integratedSecurity=false;databaseName=JavaAdv;
spring.datasource.username=sa
spring.datasource.password=SQL
server.port=8082